config/routes.rb
Gesvec::Application.routes.draw do
  resources :motorista

  resources :veiculos

  resources :permissaos

  resources :usuarios

  resources :perfils
  
  resources :perfils do
  	resources :usuarios
  	resources :permissaos
  end
  

end

app/models/permissao.rb
class Permissao < ActiveRecord::Base
	has_and_belongs_to_many :perfils 
	
end

app/controllers/permissaos_controller.rb
class PermissaosController < ApplicationController
  # GET /permissaos
  # GET /permissaos.xml
  def index
    @permissaos = Permissao.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @permissaos }
    end
  end

  # GET /permissaos/1
  # GET /permissaos/1.xml
  def show
    @permissao = Permissao.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @permissao }
    end
  end

  # GET /permissaos/new
  # GET /permissaos/new.xml
  def new
    @permissao = Permissao.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @permissao }
    end
  end

  # GET /permissaos/1/edit
  def edit
    @permissao = Permissao.find(params[:id])
  end

  # POST /permissaos
  # POST /permissaos.xml
  def create
    @permissao = Permissao.new(params[:permissao])

    respond_to do |format|
      if @permissao.save
        format.html { redirect_to(permissaos_url) }
        format.xml  { render :xml => @permissao, :status => :created, :location => @permissao }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @permissao.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /permissaos/1
  # PUT /permissaos/1.xml
  def update
    @permissao = Permissao.find(params[:id])

    respond_to do |format|
      if @permissao.update_attributes(params[:permissao])
        format.html { redirect_to(permissaos_url) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @permissao.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /permissaos/1
  # DELETE /permissaos/1.xml
  def destroy
    @permissao = Permissao.find(params[:id])
    @permissao.destroy

    respond_to do |format|
      format.html { redirect_to(permissaos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/permissaos_helper.rb
module PermissaosHelper
end

app/views/permissaos/_form.html.erb
<div id="cadastro">
	<h1>  Permissão </h1>
    <fieldset class="pequeno">
    	<legend>Cadastro de Permissões</legend>	

		<%= form_for(@permissao) do |f| %>
		  <% if @permissao.errors.any? %>
		    <div id="error_explanation">
		      <h2><%= pluralize(@permissao.errors.count, "error") %> prohibited this permissao from being saved:</h2>
		
		      <ul>
		      <% @permissao.errors.full_messages.each do |msg| %>
		        <li><%= msg %></li>
		      <% end %>
		      </ul>
		    </div>
		  <% end %>
		
		  <div class="field">
		    <%= f.label :nome %><br />
		    <%= f.text_field :nome %>
		  </div>
		  <div class="field">
		    <%= f.label :descricao %><br />
		    <%= f.text_field :descricao %>
		  </div>
		  <div class="actions">
		    <%= f.submit %>
		    <%= link_to 'Back', permissaos_path %>
		  </div>
		<% end %>
	</fieldset>	
</div>

app/views/permissaos/edit.html.erb
<%= render 'form' %>

app/views/permissaos/index.html.erb
<div id="cadastro">
	<h1>  Permissão </h1>
    <fieldset>
    	<legend>Cadastro de Permissões</legend>
		<%= link_to 'Novo', new_permissao_path, :class => "novo"  %>
      	<input type="text" name="txtPesquisa" id="txtPesquisa" />
      	<%=submit_tag 'Pesquisar'%>

		<table>
		  <tr>
		    <th>Nome</th>
		    <th>Descricao</th>
		    <th>Editar</th>
		    <th>Exibir</th>
		  </tr>
			
			<% @permissaos.each do |permissao| %>
			  <tr>
			    <td><%= permissao.nome %></td>
			    <td><%= permissao.descricao %></td>
			    <td><%= link_to 'Editar', edit_permissao_path(permissao) %></td>
			    <td><%= link_to 'Excluir', permissao, :confirm => 'Deseja excluir?', :method => :delete %></td>
			  </tr>
			<% end %>
		</table>
	</fieldset>
</div>

app/views/permissaos/new.html.erb
<h1>New permissao</h1>

<%= render 'form' %>

<%= link_to 'Back', permissaos_path %>

app/views/permissaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @permissao.nome %>
</p>

<p>
  <b>Descricao:</b>
  <%= @permissao.descricao %>
</p>


<%= link_to 'Edit', edit_permissao_path(@permissao) %> |
<%= link_to 'Back', permissaos_path %>