config/routes.rb
Gesvec::Application.routes.draw do
  resources :motorista

  resources :veiculos

  resources :permissaos

  resources :usuarios

  resources :perfils
  
  resources :perfils do
  	resources :usuarios
  	resources :permissaos
  end
  

end

app/models/veiculo.rb
class Veiculo < ActiveRecord::Base
	belongs_to :combustivel
	belongs_to :modelo
	
	validates_associated :combustivel, :modelo
	validates_presence_of :combustivel_id, :modelo_id, :placa, :chassi, :renavam
end

app/controllers/veiculos_controller.rb
class VeiculosController < ApplicationController
  # GET /veiculos
  # GET /veiculos.xml
  def index
    @veiculos = Veiculo.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @veiculos }
    end
  end

  # GET /veiculos/1
  # GET /veiculos/1.xml
  def show
    @veiculo = Veiculo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @veiculo }
    end
  end

  # GET /veiculos/new
  # GET /veiculos/new.xml
  def new
    @veiculo = Veiculo.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @veiculo }
    end
  end

  # GET /veiculos/1/edit
  def edit
    @veiculo = Veiculo.find(params[:id])
  end

  # POST /veiculos
  # POST /veiculos.xml
  def create
    @veiculo = Veiculo.new(params[:veiculo])

    respond_to do |format|
      if @veiculo.save
        format.html { redirect_to(veiculos_url) }
        format.xml  { render :xml => @veiculo, :status => :created, :location => @veiculo }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @veiculo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /veiculos/1
  # PUT /veiculos/1.xml
  def update
    @veiculo = Veiculo.find(params[:id])

    respond_to do |format|
      if @veiculo.update_attributes(params[:veiculo])
        format.html { redirect_to(veiculos_url) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @veiculo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /veiculos/1
  # DELETE /veiculos/1.xml
  def destroy
    @veiculo = Veiculo.find(params[:id])
    @veiculo.destroy

    respond_to do |format|
      format.html { redirect_to(veiculos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/veiculos_helper.rb
module VeiculosHelper
end

app/views/veiculos/_form.html.erb
<div id="cadastro">
	<h1>  Usuários </h1>
    <fieldset class="pequeno">
    	<legend>Cadastro de Usuários</legend>	

		<%= form_for(@veiculo) do |f| %>
		  <% if @veiculo.errors.any? %>
		    <div id="error_explanation">
		      <!--<h2><%= pluralize(@veiculo.errors.count, "erro") %></h2>-->
		
		      <ul>
		      <% @veiculo.errors.full_messages.each do |msg| %>
		        <li><%= msg %></li>
		      <% end %>
		      </ul>
		    </div>
		  <% end %>
		
		  <div class="field">
		    <%= f.label :placa %><br />
		    <%= f.text_field :placa %>
		  </div>
		  <div class="field">
		    <%= f.label :chassi %><br />
		    <%= f.text_field :chassi %>
		  </div>
		  <div class="field">
		    <%= f.label :renavam %><br />
		    <%= f.text_field :renavam %>
		  </div>
		  <div class="field">
		    <%= f.label :serie %><br />
		    <%= f.text_field :serie %>
		  </div>
		  <div class="field">
		    <%= f.label :Modelo %><br />
		    <%= f.collection_select(:modelo_id, Modelo.order(:nome), :id, :nome, {:prompt => ''}) %>
		  </div>
		  <div class="field">
		    <%= f.label :combustivel %><br />
		    <%= f.collection_select(:combustivel_id, Combustivel.order(:nome), :id, :nome, {:prompt => ''}) %>
		  </div>
		  <div class="field">
		    <%= f.label :ano_fabricacao %><br />
		    <%= f.text_field :ano_fabricacao %>
		  </div>
		  <div class="field">
		    <%= f.label :ano_modelo %><br />
		    <%= f.text_field :ano_modelo %>
		  </div>
		  <div class="field">
		    <%= f.label :possui_seguro %><br />
		    <%= f.check_box :possui_seguro %>
		  </div>
		  <div class="field">
		    <%= f.label :data_cadastro %><br />
		    <%= f.date_select :data_cadastro, :order => [:day,:month,:year]%>
		  </div>
		  <div class="actions">
		    <%= f.submit %>
		    <%= link_to 'Back', veiculos_path %>
		  </div>
		<% end %>
	</fieldset>
</div>		

app/views/veiculos/edit.html.erb
<%= render 'form' %>

app/views/veiculos/index.html.erb
<div id="cadastro">
	<h1>  Veículo </h1>
    <fieldset>
    	<legend>Cadastro de Veículos</legend>
    	<%= link_to 'Novo', new_veiculo_path, :class => "novo"  %>
      	<input type="text" name="txtPesquisa" id="txtPesquisa" />
      	<%=submit_tag 'Pesquisar'%>
		<table>
		  <tr>
		    <th>Placa</th>
		    <th>Modelo</th>
		    <th>Combustivel</th>
		    <th>Ano fabricacao</th>
		    <th>Ano modelo</th>
		    <th>Possui seguro</th>
		    <th>Data cadastro</th>
		    <th>Editar</th>
		    <th>Excluir</th>
		  </tr>
		
		<% @veiculos.each do |veiculo| %>
		  <tr>
		    <td><%= veiculo.placa %></td>
		    <td><%= veiculo.modelo.nome %></td>
		    <td><%= veiculo.combustivel.nome %></td>
		    <td><%= veiculo.ano_fabricacao %></td>
		    <td><%= veiculo.ano_modelo %></td>
		    <td><%= veiculo.possui_seguro %></td>
		    <td><%= veiculo.data_cadastro.to_s_br%></td>
		    <td><%= link_to 'Editar', edit_veiculo_path(veiculo) %></td>
		    <td><%= link_to 'Excluir', veiculo, :confirm => 'Deseja excluir?', :method => :delete %></td>
		  </tr>
		<% end %>
		</table>
	</fieldset>
</div>		

app/views/veiculos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Placa:</b>
  <%= @veiculo.placa %>
</p>

<p>
  <b>Chassi:</b>
  <%= @veiculo.chassi %>
</p>

<p>
  <b>Renavam:</b>
  <%= @veiculo.renavam %>
</p>

<p>
  <b>Serie:</b>
  <%= @veiculo.serie %>
</p>

<p>
  <b>Ano fabricacao:</b>
  <%= @veiculo.ano_fabricacao %>
</p>

<p>
  <b>Ano modelo:</b>
  <%= @veiculo.ano_modelo %>
</p>

<p>
  <b>Possui seguro:</b>
  <%= @veiculo.possui_seguro %>
</p>

<p>
  <b>Data cadastro:</b>
  <%= @veiculo.data_cadastro %>
</p>


<%= link_to 'Edit', edit_veiculo_path(@veiculo) %> |
<%= link_to 'Back', veiculos_path %>