config/routes.rb
Gesvec::Application.routes.draw do
  resources :motorista

  resources :veiculos

  resources :permissaos

  resources :usuarios

  resources :perfils
  
  resources :perfils do
  	resources :usuarios
  	resources :permissaos
  end
  

end

app/models/perfil.rb
class Perfil < ActiveRecord::Base
	has_many :usuarios
	has_and_belongs_to_many :permissoes
	
	validates_presence_of :nome
#	validate :validate_presence_of_more_than_one_permissao
	
#	def validate_presence_of_more_than_one_permissao
#		errors.add("permissão", "deve haver pelo menos uma permissão") if permissoes.empty?
#	end
		
end

app/controllers/perfils_controller.rb
class PerfilsController < ApplicationController
  # GET /perfils
  # GET /perfils.xml
  def index
    @perfils = Perfil.order('nome').paginate :page => params[:page], :per_page => 10
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @perfils }
    end
  end
  
  def pesquisar
  	@perfis = Perfil.find(:first)
  	respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @perfils }
    end
  end

  # GET /perfils/1
  # GET /perfils/1.xml
  def show
    @perfil = Perfil.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @perfil }
    end
  end

  # GET /perfils/new
  # GET /perfils/new.xml
  def new
    @perfil = Perfil.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @perfil }
    end
  end

  # GET /perfils/1/edit
  def edit
    @perfil = Perfil.find(params[:id])
  end

  # POST /perfils
  # POST /perfils.xml
  def create
    @perfil = Perfil.new(params[:perfil])

    respond_to do |format|
      if @perfil.save
        format.html { redirect_to(perfils_url) }
        format.xml  { render :xml => @perfils, :status => :created, :location => @perfils }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @perfil.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /perfils/1
  # PUT /perfils/1.xml
  def update
    @perfil = Perfil.find(params[:id])

    respond_to do |format|
      if @perfil.update_attributes(params[:perfil])
        format.html { redirect_to(perfils_url) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @perfil.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /perfils/1
  # DELETE /perfils/1.xml
  def destroy
    @perfil = Perfil.find(params[:id])
    @perfil.destroy

    respond_to do |format|
      format.html { redirect_to(perfils_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/perfils_helper.rb
module PerfilsHelper
end

app/views/perfils/_form.html.erb
<div id="cadastro">
	<h1>  Perfil </h1>
    <fieldset class="pequeno">
    	<legend>Cadastro de Perfis</legend>	
		<%= form_for(@perfil) do |f| %>
		  <% if @perfil.errors.any? %>
		    <div id="error_explanation">
		      <h2><%= pluralize(@perfil.errors.count, "error") %> prohibited this perfil from being saved:</h2>
		      <ul>
		      <% @perfil.errors.full_messages.each do |msg| %>
		        <li><%= msg %></li>
		      <% end %>
		      </ul>
		    </div>
		  <% end %>
		  	<div class="actions">
				<%= f.label :nome %>
				<%= f.text_field :nome %>
				<%= f.label 'Permissão'%>
				<%= f.collection_select :permissao_id, Permissao.find(:all, :order => 'nome'), :id, :nome, {}, :multiple => true %>
				<%= f.submit %>
				<%= link_to 'Voltar', perfils_path %>
		  	</div>
		<% end %>
	</fieldset>
</div>

app/views/perfils/edit.html.erb
<%= render 'form' %>

app/views/perfils/index.html.erb
<div id="cadastro">
	<h1>  Perfil </h1>
    <fieldset>
    	<legend>Cadastro de Perfis</legend>
    	<%= link_to 'Novo', new_perfil_path, :class => "novo"  %>
      	<input type="text" name="txtPesquisa" id="txtPesquisa" />
      	<%=submit_tag 'Pesquisar'%>
      	
      	<table>
		  <tr>
		    <th>Nº</th>
		    <th>Nome</th>
		    <!--<th>Exibir</th>-->
		    <th>Editar</th>
		    <th>Excluir</th>
		  </tr>
		<%cont = 0%>
		<% @perfils.each do |perfil| %>
		  <tr>
		  	<%cont = cont + 1%>
		    <td><%=  cont%></td>
		    <td><%= perfil.nome %></td>
		    <!--<td><%= link_to 'Mostrar', perfil%></td>-->
		    <td><%= link_to 'Editar', edit_perfil_path(perfil), :class=>'editar' %></td>
		    <td><%= link_to 'Excluir', perfil, :method => :delete, :confirm => "Deseja exluir?", :class=>'excluir' %></td>
		  </tr>
		<% end %>
		</table>
		<br />
		<%= will_paginate @perfils%>
    </fieldset>  	
<div>

app/views/perfils/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @perfil.id %>
</p>

<p>
  <b>Nome:</b>
  <%= @perfil.nome %>
</p>


<%= link_to 'Edit', edit_perfil_path(@perfil) %> |
<%= link_to 'Back', perfils_path %>