config/routes.rb
Gesvec::Application.routes.draw do
  resources :motorista

  resources :veiculos

  resources :permissaos

  resources :usuarios

  resources :perfils
  
  resources :perfils do
  	resources :usuarios
  	resources :permissaos
  end
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gesvec</title>
  <%= stylesheet_link_tag 'estilo' %>
  <link />
  <%= stylesheet_link_tag 'autocomplete' %>
  <%= stylesheet_link_tag 'calendar/jquery-ui-1.7.2.custom' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
	<div id="main">
		<div id="topo">
      		<img src="/images/fortaleza-bela.gif" alt="Logo da Administração" width="250" height="80" />
      		<h1> Sistema de Controle de Frotas </h1>
      		<h2>Prefeitura Municipal de Fortaleza</h2>
    	</div>
  		<div id="info">
	    	<dl>
	      		<dt>Usu&aacute;rio:</dt> 
	      		<dd>Lorem Ipsum Domini</dd>
	      		<dt>Grupo:</dt>
	      		<dd>Agnus</dd>
	    	</dl>
  		</div>
  		<div id="menu">
  			<ul>
  				<li><a href="javascript:void(0)">Atividades</a>
		        	<ul>
			          <li><a href="javascript:void(0)">Diário de bomba</a></li>
			          <li><a href="javascript:void(0)">Abastecimento</a></li>
		        	</ul>
		      	</li>
  				<li><a href="javascript:void(0)">Cadastros</a>
		        	<ul>
			          <li><%= link_to 'Motorista', motorista_path %></li>
			          <li><%= link_to 'Veículo', veiculos_path %></li>
		        	</ul>
		      	</li>
		    	<li><a href="javascript:void(0)">Administração</a>
		        	<ul>
			          <li><%= link_to 'Perfil', perfils_path %></li>
			          <li><%= link_to 'Usuario', usuarios_path %></li>
			          <li><%= link_to 'Permissão', permissaos_path %></li>
		        	</ul>
		      	</li>
		      	<li><a href="javascript:void(0)">Sair</a></li>
		    </ul>  
  		</div>
		<%= yield %>
		<div id="rodape">
    		Sistema adquirido com recursos do PNAFM
    		<span class="versao"> V 2.1 </span>
  		</div>
	</div>
	<%= javascript_include_tag 'jquery-1.3.2.min.js' %>
	<%= javascript_include_tag 'jquery.meio.mask.js' %>
	<%= javascript_include_tag 'jquery-ui-1.7.2.custom.min.js' %>
	<%= javascript_include_tag 'jquery.validate.js' %>
	<%= javascript_include_tag 'funcoes.js' %>
	<%= javascript_include_tag 'jquery.autocomplete.js' %>
	<%= javascript_include_tag 'jquery.select-autocomplete.js' %>
	
</body>
</html>